spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_mybatis
    username: root
    password: wangli222222
    driver-class-name: com.mysql.jdbc.Driver
#“≥√Ê»»º”‘ÿ
  thymeleaf:
    cache: false
server:
  port: 8888